project_id = "djijqykpyfjjzxhhefij"

[functions.battlenet-auth]
verify_jwt = false

[functions.submit-bug-report]
verify_jwt = false

[functions.sync-wow-spells]
verify_jwt = false

[functions.guild-vault]
verify_jwt = false
