import type {
  CompositionAbilityAnalyticsRow,
  CompositionAbilityMappingAnalyticsRow,
} from '@/lib/compositionAnalytics';
import type { RaidEffectAnalyticsRow, WowSpellAnalyticsRow } from '@/lib/raidEffectAnalytics';

type AbilitySeed = readonly [
  abilityKey: string,
  coverageKey: string,
  abilityKind: CompositionAbilityAnalyticsRow['ability_kind'],
  spellId: number | null,
  sortOrder: number,
];

type MappingSeed = readonly [
  abilityKey: string,
  classId: string,
  specId?: string | null,
  role?: string | null,
];

type RaidEffectSeed = readonly [
  classId: string,
  specId: string | null,
  category: 'major_buff' | 'major_debuff',
  spellId: number,
  effectKey: string,
  sortOrder: number,
];

type SpellSeed = readonly [spellId: number, name: string, description?: string];

const spell = ([spell_id, name, description = '']: SpellSeed): WowSpellAnalyticsRow => ({
  spell_id,
  name_en: name,
  description_en: description,
  name_fr: name,
  description_fr: description,
  name_de: name,
  description_de: description,
  name_es: name,
  description_es: description,
  name_pt_br: name,
  description_pt_br: description,
  name_it: name,
  description_it: description,
  name_ru: name,
  description_ru: description,
  name_zh_tw: name,
  description_zh_tw: description,
  name_ko: name,
  description_ko: description,
});

const ability = ([ability_key, coverage_key, ability_kind, spell_id, sort_order]: AbilitySeed): CompositionAbilityAnalyticsRow => ({
  id: ability_key,
  ability_key,
  coverage_key,
  ability_kind,
  spell_id,
  cooldown_profile: null,
  cooldown_seconds: null,
  active: true,
  sort_order,
});

const mapping = ([ability_id, class_id, spec_id = null, role = null]: MappingSeed): CompositionAbilityMappingAnalyticsRow => ({
  ability_id,
  class_id,
  spec_id,
  role,
  applies_to_main: true,
  applies_to_offspec_alt: false,
});

const raidEffect = ([class_id, spec_id, category, spell_id, effect_key, sort_order]: RaidEffectSeed): RaidEffectAnalyticsRow => ({
  class_id,
  spec_id,
  category,
  spell_id,
  effect_key,
  sort_order,
});

const raidEffectSeeds: RaidEffectSeed[] = [
  ['druid', null, 'major_buff', 1126, 'mark_of_the_wild', 70],
  ['mage', null, 'major_buff', 1459, 'arcane_intellect', 10],
  ['warrior', null, 'major_buff', 6673, 'battle_shout', 20],
  ['evoker', null, 'major_buff', 364342, 'blessing_of_the_bronze', 80],
  ['shaman', null, 'major_buff', 2825, 'bloodlust', 90],
  ['warlock', null, 'major_buff', 29893, 'soulwell', 100],
  ['paladin', null, 'major_buff', 465, 'devotion_aura', 40],
  ['priest', null, 'major_buff', 21562, 'power_word_fortitude', 30],
  ['shaman', null, 'major_buff', 462854, 'skyfury', 110],
  ['evoker', 'evoker-augmentation', 'major_buff', 395152, 'ebon_might', 140],
  ['shaman', null, 'major_buff', 32182, 'heroism', 91],
  ['mage', null, 'major_buff', 80353, 'time_warp', 92],
  ['hunter', null, 'major_buff', 264667, 'primal_rage', 93],
  ['evoker', null, 'major_buff', 390386, 'fury_of_the_aspects', 94],
  ['monk', null, 'major_debuff', 8647, 'mystic_touch', 50],
  ['demon-hunter', null, 'major_debuff', 255260, 'chaos_brand', 60],
  ['hunter', null, 'major_debuff', 257284, 'hunters_mark', 120],
  ['rogue', null, 'major_debuff', 381637, 'atrophic_poison', 130],
];

const abilitySeeds: AbilitySeed[] = [
  ['arcane_intellect', 'arcane_intellect', 'raid_buff', 1459, 10],
  ['battle_shout', 'battle_shout', 'raid_buff', 6673, 20],
  ['power_word_fortitude', 'power_word_fortitude', 'raid_buff', 21562, 30],
  ['skyfury', 'skyfury', 'raid_utility', 462854, 220],
  ['mark_of_the_wild', 'mark_of_the_wild', 'raid_buff', 1126, 50],
  ['mystic_touch', 'mystic_touch', 'raid_debuff', 8647, 60],
  ['chaos_brand', 'chaos_brand', 'raid_debuff', 255260, 70],
  ['hunters_mark', 'hunters_mark', 'raid_debuff', 257284, 80],
  ['atrophic_poison', 'atrophic_poison', 'raid_debuff', 381637, 90],
  ['blessing_of_the_bronze', 'blessing_of_the_bronze', 'raid_utility', 364342, 240],
  ['bloodlust', 'bloodlust', 'raid_utility', 2825, 110],
  ['heroism', 'bloodlust', 'raid_utility', 32182, 111],
  ['time_warp', 'bloodlust', 'raid_utility', 80353, 112],
  ['primal_rage', 'bloodlust', 'raid_utility', 264667, 113],
  ['fury_of_the_aspects', 'bloodlust', 'raid_utility', 390386, 114],
  ['soulwell', 'soulwell', 'raid_buff', 29893, 141],
  ['devotion_aura', 'devotion_aura', 'raid_defensive', 465, 130],
  ['ebon_might', 'ebon_might', 'external', 395152, 140],
  ['rebirth', 'combat_res', 'raid_utility', 20484, 120],
  ['raise_ally', 'combat_res', 'raid_utility', 61999, 121],
  ['soulstone', 'combat_res', 'raid_utility', 20707, 122],
  ['intercession', 'combat_res', 'raid_utility', 391054, 123],
  ['stampeding_roar', 'burst_move_speed', 'raid_utility', 106898, 130],
  ['wind_rush_totem', 'burst_move_speed', 'raid_utility', 192077, 131],
  ['zephyr', 'burst_move_speed', 'raid_utility', 374227, 132],
  ['demonic_gateway', 'demonic_gateway', 'raid_utility', 111771, 140],
  ['mass_dispel', 'mass_dispel', 'raid_utility', 32375, 150],
  ['innervate', 'innervate', 'external', 29166, 160],
  ['death_grip', 'death_grip', 'raid_utility', 49576, 170],
  ['blessing_of_protection', 'external_defensives', 'external', 1022, 186],
  ['blessing_of_spellwarding', 'external_defensives', 'external', 204018, 187],
  ['ironbark_external_defensive', 'external_defensives', 'external', 102342, 180],
  ['life_cocoon_external_defensive', 'external_defensives', 'external', 116849, 181],
  ['time_dilation_external_defensive', 'external_defensives', 'external', 357170, 182],
  ['pain_suppression_external_defensive', 'external_defensives', 'external', 33206, 183],
  ['guardian_spirit_external_defensive', 'external_defensives', 'external', 47788, 184],
  ['blessing_of_sacrifice_external_defensive', 'external_defensives', 'external', 6940, 185],
  ['intervene_external_defensive', 'external_defensives', 'external', 3411, 188],
  ['anti_magic_zone', 'raid_defensives', 'raid_defensive', 51052, 191],
  ['rallying_cry', 'raid_defensives', 'raid_defensive', 97462, 192],
  ['darkness', 'raid_defensives', 'raid_defensive', 196718, 193],
  ['zephyr_raid_defensive', 'raid_defensives', 'raid_defensive', 374227, 194],
  ['aegis_of_light_raid_defensive', 'raid_defensives', 'raid_defensive', 204150, 196],
  ['ice_block', 'immunity', 'raid_defensive', 45438, 210],
  ['divine_shield', 'immunity', 'raid_defensive', 642, 211],
  ['aspect_of_the_turtle', 'immunity', 'raid_defensive', 186265, 212],
  ['cloak_of_shadows', 'immunity', 'raid_defensive', 31224, 213],
  ['netherwalk', 'immunity', 'raid_defensive', 196555, 214],
  ['dispersion', 'immunity', 'raid_defensive', 47585, 215],
  ['atrophic_poison_boss_dr', 'boss_damage_reduction', 'raid_utility', 381637, 230],
  ['execute_warrior_arms', 'execute_damage', 'raid_utility', 163201, 250],
  ['shadow_word_death', 'execute_damage', 'raid_utility', 32379, 252],
  ['kill_shot', 'execute_damage', 'raid_utility', 53351, 253],
  ['hammer_of_wrath', 'execute_damage', 'raid_utility', 24275, 254],
  ['touch_of_death', 'execute_damage', 'raid_utility', 322109, 255],
  ['curse_of_weakness_attack_speed', 'warlock_curses', 'raid_utility', 702, 260],
  ['curse_of_tongues_cast_speed', 'warlock_curses', 'raid_utility', 1714, 261],
  ['typhoon_knock', 'knockbacks', 'raid_utility', 132469, 280],
  ['thunderstorm_knock', 'knockbacks', 'raid_utility', 51490, 281],
  ['ring_of_peace_knock', 'knockbacks', 'raid_utility', 116844, 282],
  ['wing_buffet_knock', 'knockbacks', 'raid_utility', 357214, 283],
  ['tail_swipe_knock', 'knockups', 'raid_utility', 368970, 284],
  ['thundershock_knockup', 'knockups', 'raid_utility', 378779, 285],
  ['mortal_strike', 'mortal_strike', 'raid_utility', 12294, 290],
  ['wound_poison_mortal_wounds', 'mortal_strike', 'raid_utility', 8679, 291],
  ['rising_sun_kick_mortal_wounds', 'mortal_strike', 'raid_utility', 107428, 292],
  ['soothe', 'soothe', 'raid_utility', 2908, 300],
  ['tranquilizing_shot_soothe', 'soothe', 'raid_utility', 19801, 301],
  ['shiv_soothe', 'soothe', 'raid_utility', 5938, 302],
  ['purge', 'purge', 'raid_utility', 370, 310],
  ['dispel_magic_purge', 'purge', 'raid_utility', 528, 311],
  ['spellsteal_purge', 'purge', 'raid_utility', 30449, 312],
  ['consume_magic_purge', 'purge', 'raid_utility', 278326, 313],
  ['power_infusion', 'power_infusion', 'external', 10060, 320],
  ['shattering_throw_extra_shield_damage', 'extra_damage_to_shields', 'raid_utility', 64382, 330],
  ['wrecking_throw_extra_shield_damage', 'extra_damage_to_shields', 'raid_utility', 384110, 331],
  ['unravel_extra_shield_damage', 'extra_damage_to_shields', 'raid_utility', 1264378, 332],
  ['devour_matter_extra_shield_damage', 'extra_damage_to_shields', 'raid_utility', 451840, 333],
  ['cheat_death', 'cheat_death', 'raid_defensive', 31230, 340],
  ['cauterize_cheat_death', 'cheat_death', 'raid_defensive', 86949, 341],
  ['purgatory_cheat_death', 'cheat_death', 'raid_defensive', 114556, 342],
  ['last_resort_cheat_death', 'cheat_death', 'raid_defensive', 209258, 343],
  ['chaos_nova_aoe_stun', 'aoe_stuns', 'raid_utility', 179057, 360],
  ['void_nova_aoe_stun', 'aoe_stuns', 'raid_utility', 1234195, 361],
  ['leg_sweep_aoe_stun', 'aoe_stuns', 'raid_utility', 119381, 362],
  ['capacitor_totem_aoe_stun', 'aoe_stuns', 'raid_utility', 192058, 363],
  ['shadowfury_aoe_stun', 'aoe_stuns', 'raid_utility', 30283, 364],
  ['binding_shot_aoe_stun', 'aoe_stuns', 'raid_utility', 117526, 365],
  ['shockwave_aoe_stun', 'aoe_stuns', 'raid_utility', 46968, 366],
  ['mass_entanglement_aoe_root', 'aoe_roots', 'raid_utility', 102359, 370],
  ['entangling_vortex_aoe_root', 'aoe_roots', 'raid_utility', 439895, 371],
  ['landslide_aoe_root', 'aoe_roots', 'raid_utility', 358385, 372],
  ['frost_nova_aoe_root', 'aoe_roots', 'raid_utility', 122, 373],
  ['void_tendrils_aoe_root', 'aoe_roots', 'raid_utility', 1250691, 374],
  ['earthgrab_totem_aoe_root', 'aoe_roots', 'raid_utility', 51485, 375],
  ['sigil_of_chains_aoe_slow', 'aoe_slows', 'raid_utility', 202138, 380],
  ['wave_of_debilitation_aoe_slow', 'aoe_slows', 'raid_utility', 452403, 381],
  ['typhoon_aoe_slow', 'aoe_slows', 'raid_utility', 132469, 382],
  ['ursols_vortex_aoe_slow', 'aoe_slows', 'raid_utility', 102793, 383],
  ['tail_swipe_aoe_slow', 'aoe_slows', 'raid_utility', 368970, 384],
  ['wing_buffet_aoe_slow', 'aoe_slows', 'raid_utility', 357214, 385],
  ['tar_trap_aoe_slow', 'aoe_slows', 'raid_utility', 187698, 386],
  ['earthbind_totem_aoe_slow', 'aoe_slows', 'raid_utility', 2484, 387],
  ['earthgrab_totem_aoe_slow', 'aoe_slows', 'raid_utility', 51485, 388],
  ['thunderstorm_aoe_slow', 'aoe_slows', 'raid_utility', 51490, 389],
  ['piercing_howl_aoe_slow', 'aoe_slows', 'raid_utility', 12323, 390],
  ['boneshaker_aoe_slow', 'aoe_slows', 'raid_utility', 429639, 391],
  ['death_grip_enemy_grouping', 'enemy_grips_and_grouping', 'raid_utility', 49576, 400],
  ['gorefiends_grasp', 'enemy_grips_and_grouping', 'raid_utility', 108199, 401],
  ['abomination_limb', 'enemy_grips_and_grouping', 'raid_utility', 315443, 402],
  ['misdirection', 'threat_redirection', 'raid_utility', 34477, 410],
  ['tricks_of_the_trade', 'threat_redirection', 'raid_utility', 57934, 411],
  ['solar_beam', 'silences_and_anti_cast', 'raid_utility', 78675, 420],
  ['sigil_of_silence', 'silences_and_anti_cast', 'raid_utility', 202137, 421],
  ['silence_priest', 'silences_and_anti_cast', 'raid_utility', 15487, 422],
  ['wailing_arrow', 'silences_and_anti_cast', 'raid_utility', 392060, 423],
  ['blessing_of_freedom', 'ally_freedom_and_mobility', 'raid_utility', 1044, 430],
  ['tigers_lust', 'ally_freedom_and_mobility', 'raid_utility', 116841, 431],
  ['masters_call', 'ally_freedom_and_mobility', 'raid_utility', 53271, 432],
  ['rescue_evoker', 'ally_freedom_and_mobility', 'raid_utility', 370665, 433],
  ['leap_of_faith', 'ally_freedom_and_mobility', 'raid_utility', 73325, 434],
  ['angelic_feather', 'ally_freedom_and_mobility', 'raid_utility', 121536, 435],
  ['mind_freeze_interrupt', 'interrupts', 'raid_utility', 47528, 450],
  ['disrupt_interrupt', 'interrupts', 'raid_utility', 183752, 451],
  ['skull_bash_interrupt', 'interrupts', 'raid_utility', 106839, 452],
  ['quell_interrupt', 'interrupts', 'raid_utility', 351338, 453],
  ['counter_shot_interrupt', 'interrupts', 'raid_utility', 147362, 454],
  ['muzzle_interrupt', 'interrupts', 'raid_utility', 187707, 455],
  ['counterspell_interrupt', 'interrupts', 'raid_utility', 2139, 456],
  ['spear_hand_strike_interrupt', 'interrupts', 'raid_utility', 116705, 457],
  ['rebuke_interrupt', 'interrupts', 'raid_utility', 96231, 458],
  ['kick_interrupt', 'interrupts', 'raid_utility', 1766, 459],
  ['wind_shear_interrupt', 'interrupts', 'raid_utility', 57994, 460],
  ['spell_lock_interrupt', 'interrupts', 'raid_utility', 19647, 461],
  ['axe_toss_interrupt', 'interrupts', 'raid_utility', 89766, 462],
  ['pummel_interrupt', 'interrupts', 'raid_utility', 6552, 463],
  ['cleanse_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 4987, 520],
  ['natures_cure_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 88423, 521],
  ['naturalize_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 360823, 522],
  ['detox_mistweaver_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 115450, 523],
  ['purify_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 527, 524],
  ['purify_spirit_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 254420, 525],
  ['mass_dispel_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 32375, 526],
  ['revival_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 115310, 527],
  ['singe_magic_ally_magic_dispel', 'ally_magic_dispels', 'raid_utility', 89808, 528],
  ['remove_corruption_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 2782, 530],
  ['natures_cure_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 88423, 531],
  ['cauterizing_flame_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 374251, 532],
  ['remove_curse_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 475, 533],
  ['cleanse_spirit_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 51886, 534],
  ['purify_spirit_ally_curse_dispel', 'ally_curse_dispels', 'raid_utility', 254420, 535],
  ['remove_corruption_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 2782, 540],
  ['natures_cure_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 88423, 541],
  ['expunge_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 365585, 542],
  ['naturalize_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 360823, 543],
  ['cauterizing_flame_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 374251, 544],
  ['detox_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 218164, 545],
  ['detox_mistweaver_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 115450, 546],
  ['revival_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 115310, 547],
  ['restoral_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 388615, 548],
  ['cleanse_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 4987, 549],
  ['cleanse_toxins_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 213644, 550],
  ['poison_cleansing_totem_ally_poison_dispel', 'ally_poison_dispels', 'raid_utility', 383013, 551],
  ['cauterizing_flame_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 374251, 560],
  ['detox_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 218164, 561],
  ['detox_mistweaver_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 115450, 562],
  ['revival_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 115310, 563],
  ['restoral_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 388615, 564],
  ['cleanse_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 4987, 565],
  ['cleanse_toxins_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 213644, 566],
  ['purify_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 527, 567],
  ['purify_disease_ally_disease_dispel', 'ally_disease_dispels', 'raid_utility', 213634, 568],
  ['cauterizing_flame_ally_bleed_dispel', 'ally_bleed_dispels', 'raid_utility', 374251, 570],
  ['blessing_of_freedom_ally_roots_snares_dispel', 'ally_roots_snares_dispels', 'raid_utility', 1044, 590],
  ['tigers_lust_ally_roots_snares_dispel', 'ally_roots_snares_dispels', 'raid_utility', 116841, 591],
  ['masters_call_ally_roots_snares_dispel', 'ally_roots_snares_dispels', 'raid_utility', 53271, 592],
  ['tremor_totem_ally_fear_dispel', 'ally_fear_dispels', 'raid_utility', 8143, 580],
  ['berserker_shout_ally_fear_dispel', 'ally_fear_dispels', 'raid_utility', 384100, 581],
  ['tremor_totem_ally_charm_sleep_dispel', 'ally_charm_sleep_dispels', 'raid_utility', 8143, 582],
];

const mappingSeeds: MappingSeed[] = [
  ['arcane_intellect', 'mage'],
  ['battle_shout', 'warrior'],
  ['power_word_fortitude', 'priest'],
  ['skyfury', 'shaman'],
  ['mark_of_the_wild', 'druid'],
  ['mystic_touch', 'monk'],
  ['chaos_brand', 'demon-hunter'],
  ['hunters_mark', 'hunter'],
  ['atrophic_poison', 'rogue'],
  ['blessing_of_the_bronze', 'evoker'],
  ['bloodlust', 'shaman'],
  ['heroism', 'shaman'],
  ['time_warp', 'mage'],
  ['primal_rage', 'hunter'],
  ['fury_of_the_aspects', 'evoker'],
  ['soulwell', 'warlock'],
  ['devotion_aura', 'paladin'],
  ['ebon_might', 'evoker', 'evoker-augmentation'],
  ['rebirth', 'druid'],
  ['raise_ally', 'death-knight'],
  ['soulstone', 'warlock'],
  ['intercession', 'paladin'],
  ['stampeding_roar', 'druid'],
  ['wind_rush_totem', 'shaman'],
  ['zephyr', 'evoker'],
  ['demonic_gateway', 'warlock'],
  ['mass_dispel', 'priest'],
  ['innervate', 'druid'],
  ['death_grip', 'death-knight'],
  ['blessing_of_protection', 'paladin'],
  ['blessing_of_spellwarding', 'paladin', 'paladin-protection'],
  ['ironbark_external_defensive', 'druid', 'druid-restoration'],
  ['life_cocoon_external_defensive', 'monk', 'monk-mistweaver'],
  ['time_dilation_external_defensive', 'evoker', 'evoker-preservation'],
  ['pain_suppression_external_defensive', 'priest', 'priest-discipline'],
  ['guardian_spirit_external_defensive', 'priest', 'priest-holy'],
  ['blessing_of_sacrifice_external_defensive', 'paladin'],
  ['intervene_external_defensive', 'warrior'],
  ['anti_magic_zone', 'death-knight'],
  ['rallying_cry', 'warrior'],
  ['darkness', 'demon-hunter'],
  ['zephyr_raid_defensive', 'evoker'],
  ['aegis_of_light_raid_defensive', 'paladin', 'paladin-protection'],
  ['ice_block', 'mage'],
  ['divine_shield', 'paladin'],
  ['aspect_of_the_turtle', 'hunter'],
  ['cloak_of_shadows', 'rogue'],
  ['netherwalk', 'demon-hunter'],
  ['dispersion', 'priest', 'priest-shadow'],
  ['atrophic_poison_boss_dr', 'rogue'],
  ['execute_warrior_arms', 'warrior', 'warrior-arms'],
  ['shadow_word_death', 'priest'],
  ['kill_shot', 'hunter'],
  ['hammer_of_wrath', 'paladin'],
  ['touch_of_death', 'monk'],
  ['curse_of_weakness_attack_speed', 'warlock'],
  ['curse_of_tongues_cast_speed', 'warlock'],
  ['typhoon_knock', 'druid'],
  ['thunderstorm_knock', 'shaman'],
  ['ring_of_peace_knock', 'monk'],
  ['wing_buffet_knock', 'evoker'],
  ['tail_swipe_knock', 'evoker'],
  ['thundershock_knockup', 'shaman'],
  ['mortal_strike', 'warrior', 'warrior-arms'],
  ['wound_poison_mortal_wounds', 'rogue'],
  ['rising_sun_kick_mortal_wounds', 'monk', 'monk-windwalker'],
  ['soothe', 'druid'],
  ['tranquilizing_shot_soothe', 'hunter'],
  ['shiv_soothe', 'rogue'],
  ['purge', 'shaman'],
  ['dispel_magic_purge', 'priest'],
  ['spellsteal_purge', 'mage'],
  ['consume_magic_purge', 'demon-hunter'],
  ['power_infusion', 'priest'],
  ['shattering_throw_extra_shield_damage', 'warrior'],
  ['wrecking_throw_extra_shield_damage', 'warrior'],
  ['unravel_extra_shield_damage', 'evoker'],
  ['devour_matter_extra_shield_damage', 'priest', 'priest-discipline'],
  ['devour_matter_extra_shield_damage', 'priest', 'priest-shadow'],
  ['cheat_death', 'rogue'],
  ['cauterize_cheat_death', 'mage', 'mage-fire'],
  ['purgatory_cheat_death', 'death-knight', 'dk-blood'],
  ['last_resort_cheat_death', 'demon-hunter', 'dh-vengeance'],
  ['chaos_nova_aoe_stun', 'demon-hunter', 'dh-havoc'],
  ['chaos_nova_aoe_stun', 'demon-hunter', 'dh-vengeance'],
  ['void_nova_aoe_stun', 'demon-hunter'],
  ['leg_sweep_aoe_stun', 'monk'],
  ['capacitor_totem_aoe_stun', 'shaman'],
  ['shadowfury_aoe_stun', 'warlock'],
  ['binding_shot_aoe_stun', 'hunter'],
  ['shockwave_aoe_stun', 'warrior'],
  ['mass_entanglement_aoe_root', 'druid'],
  ['entangling_vortex_aoe_root', 'druid'],
  ['landslide_aoe_root', 'evoker'],
  ['frost_nova_aoe_root', 'mage'],
  ['void_tendrils_aoe_root', 'priest'],
  ['earthgrab_totem_aoe_root', 'shaman'],
  ['sigil_of_chains_aoe_slow', 'demon-hunter'],
  ['wave_of_debilitation_aoe_slow', 'demon-hunter'],
  ['typhoon_aoe_slow', 'druid'],
  ['ursols_vortex_aoe_slow', 'druid'],
  ['tail_swipe_aoe_slow', 'evoker'],
  ['wing_buffet_aoe_slow', 'evoker'],
  ['tar_trap_aoe_slow', 'hunter'],
  ['earthbind_totem_aoe_slow', 'shaman'],
  ['earthgrab_totem_aoe_slow', 'shaman'],
  ['thunderstorm_aoe_slow', 'shaman'],
  ['piercing_howl_aoe_slow', 'warrior'],
  ['boneshaker_aoe_slow', 'warrior'],
  ['death_grip_enemy_grouping', 'death-knight'],
  ['gorefiends_grasp', 'death-knight', 'dk-blood'],
  ['abomination_limb', 'death-knight'],
  ['misdirection', 'hunter'],
  ['tricks_of_the_trade', 'rogue'],
  ['solar_beam', 'druid', 'druid-balance'],
  ['sigil_of_silence', 'demon-hunter', 'dh-vengeance'],
  ['silence_priest', 'priest', 'priest-shadow'],
  ['wailing_arrow', 'hunter', 'hunter-beast-mastery'],
  ['wailing_arrow', 'hunter', 'hunter-marksmanship'],
  ['blessing_of_freedom', 'paladin'],
  ['tigers_lust', 'monk'],
  ['masters_call', 'hunter'],
  ['rescue_evoker', 'evoker'],
  ['leap_of_faith', 'priest'],
  ['angelic_feather', 'priest'],
  ['mind_freeze_interrupt', 'death-knight'],
  ['disrupt_interrupt', 'demon-hunter'],
  ['skull_bash_interrupt', 'druid', 'druid-feral'],
  ['skull_bash_interrupt', 'druid', 'druid-guardian'],
  ['quell_interrupt', 'evoker', 'evoker-devastation'],
  ['quell_interrupt', 'evoker', 'evoker-augmentation'],
  ['counter_shot_interrupt', 'hunter', 'hunter-beast-mastery'],
  ['counter_shot_interrupt', 'hunter', 'hunter-marksmanship'],
  ['muzzle_interrupt', 'hunter', 'hunter-survival'],
  ['counterspell_interrupt', 'mage'],
  ['spear_hand_strike_interrupt', 'monk', 'monk-brewmaster'],
  ['spear_hand_strike_interrupt', 'monk', 'monk-windwalker'],
  ['rebuke_interrupt', 'paladin', 'paladin-protection'],
  ['rebuke_interrupt', 'paladin', 'paladin-retribution'],
  ['kick_interrupt', 'rogue'],
  ['wind_shear_interrupt', 'shaman'],
  ['spell_lock_interrupt', 'warlock', 'warlock-affliction'],
  ['spell_lock_interrupt', 'warlock', 'warlock-destruction'],
  ['axe_toss_interrupt', 'warlock', 'warlock-demonology'],
  ['pummel_interrupt', 'warrior'],
  ['cleanse_ally_magic_dispel', 'paladin', 'paladin-holy'],
  ['natures_cure_ally_magic_dispel', 'druid', 'druid-restoration'],
  ['naturalize_ally_magic_dispel', 'evoker', 'evoker-preservation'],
  ['detox_mistweaver_ally_magic_dispel', 'monk', 'monk-mistweaver'],
  ['purify_ally_magic_dispel', 'priest', 'priest-discipline'],
  ['purify_ally_magic_dispel', 'priest', 'priest-holy'],
  ['purify_spirit_ally_magic_dispel', 'shaman', 'shaman-restoration'],
  ['mass_dispel_ally_magic_dispel', 'priest'],
  ['revival_ally_magic_dispel', 'monk', 'monk-mistweaver'],
  ['singe_magic_ally_magic_dispel', 'warlock'],
  ['remove_corruption_ally_curse_dispel', 'druid', 'druid-balance'],
  ['remove_corruption_ally_curse_dispel', 'druid', 'druid-feral'],
  ['remove_corruption_ally_curse_dispel', 'druid', 'druid-guardian'],
  ['natures_cure_ally_curse_dispel', 'druid', 'druid-restoration'],
  ['cauterizing_flame_ally_curse_dispel', 'evoker'],
  ['remove_curse_ally_curse_dispel', 'mage'],
  ['cleanse_spirit_ally_curse_dispel', 'shaman', 'shaman-elemental'],
  ['cleanse_spirit_ally_curse_dispel', 'shaman', 'shaman-enhancement'],
  ['purify_spirit_ally_curse_dispel', 'shaman', 'shaman-restoration'],
  ['remove_corruption_ally_poison_dispel', 'druid', 'druid-balance'],
  ['remove_corruption_ally_poison_dispel', 'druid', 'druid-feral'],
  ['remove_corruption_ally_poison_dispel', 'druid', 'druid-guardian'],
  ['natures_cure_ally_poison_dispel', 'druid', 'druid-restoration'],
  ['expunge_ally_poison_dispel', 'evoker', 'evoker-devastation'],
  ['expunge_ally_poison_dispel', 'evoker', 'evoker-augmentation'],
  ['naturalize_ally_poison_dispel', 'evoker', 'evoker-preservation'],
  ['cauterizing_flame_ally_poison_dispel', 'evoker'],
  ['detox_ally_poison_dispel', 'monk', 'monk-brewmaster'],
  ['detox_ally_poison_dispel', 'monk', 'monk-windwalker'],
  ['detox_mistweaver_ally_poison_dispel', 'monk', 'monk-mistweaver'],
  ['revival_ally_poison_dispel', 'monk', 'monk-mistweaver'],
  ['restoral_ally_poison_dispel', 'monk', 'monk-mistweaver'],
  ['cleanse_ally_poison_dispel', 'paladin', 'paladin-holy'],
  ['cleanse_toxins_ally_poison_dispel', 'paladin', 'paladin-protection'],
  ['cleanse_toxins_ally_poison_dispel', 'paladin', 'paladin-retribution'],
  ['poison_cleansing_totem_ally_poison_dispel', 'shaman'],
  ['cauterizing_flame_ally_disease_dispel', 'evoker'],
  ['detox_ally_disease_dispel', 'monk', 'monk-brewmaster'],
  ['detox_ally_disease_dispel', 'monk', 'monk-windwalker'],
  ['detox_mistweaver_ally_disease_dispel', 'monk', 'monk-mistweaver'],
  ['revival_ally_disease_dispel', 'monk', 'monk-mistweaver'],
  ['restoral_ally_disease_dispel', 'monk', 'monk-mistweaver'],
  ['cleanse_ally_disease_dispel', 'paladin', 'paladin-holy'],
  ['cleanse_toxins_ally_disease_dispel', 'paladin', 'paladin-protection'],
  ['cleanse_toxins_ally_disease_dispel', 'paladin', 'paladin-retribution'],
  ['purify_ally_disease_dispel', 'priest', 'priest-discipline'],
  ['purify_ally_disease_dispel', 'priest', 'priest-holy'],
  ['purify_disease_ally_disease_dispel', 'priest', 'priest-shadow'],
  ['cauterizing_flame_ally_bleed_dispel', 'evoker'],
  ['blessing_of_freedom_ally_roots_snares_dispel', 'paladin'],
  ['tigers_lust_ally_roots_snares_dispel', 'monk'],
  ['masters_call_ally_roots_snares_dispel', 'hunter'],
  ['tremor_totem_ally_fear_dispel', 'shaman'],
  ['berserker_shout_ally_fear_dispel', 'warrior'],
  ['tremor_totem_ally_charm_sleep_dispel', 'shaman'],
];

const spellSeeds: SpellSeed[] = [
  [1126, "Mark of the Wild", "Infuse a friendly target with the power of the wild, increasing their Versatility by 3% for 60 minutes.\r\n\r\nIf target is in your party or raid, all party and raid members will be affected.\r\n"],
  [1459, "Arcane Intellect", "Infuses the target with brilliance, increasing their Intellect by 3% for 1 hour.  \r\n\r\nIf the target is in your party or raid, all party and raid members will be affected."],
  [6673, "Battle Shout", "Increases the attack power of all raid and party members within 100 yards by 5% for 1 hour."],
  [364342, "Blessing of the Bronze", "Weave the threads of time, reducing the cooldown of a major movement ability for all party and raid members by 15% for 1 hour."],
  [2825, "Bloodlust", "Increases haste by 30% for all party and raid members for 40 sec.\r\n\r\nAllies receiving this effect will become Sated and unable to benefit from Bloodlust or Time Warp again for 10 min."],
  [32182, "Heroism", "Increases haste by 30% for all party and raid members for 40 sec.\r\n\r\nAllies receiving this effect will become Exhausted and unable to benefit from Heroism or Time Warp again for 10 min."],
  [80353, "Time Warp", "Warp the flow of time, increasing haste by 30% for all party and raid members for 40 sec.\r\n\r\nAllies will be unable to benefit from Bloodlust, Heroism, or Time Warp again for 10 min."],
  [264667, "Primal Rage", "Increases haste by 30% for all party and raid members for 40 sec.\r\n\r\nAllies receiving this effect will become Sated and unable to benefit from Primal Rage or similar effects again for 10 min."],
  [390386, "Fury of the Aspects", "Increases haste by 30% for all party and raid members for 40 sec.\r\n\r\nAllies receiving this effect will become Exhausted and unable to benefit from Fury of the Aspects or similar effects again for 10 min."],
  [29893, "Create Soulwell", "Creates a Soulwell for 2 min. Party and raid members can use the Soulwell to acquire a Healthstone."],
  [465, "Devotion Aura", "Party and raid members within 40 yds are bolstered by their devotion, reducing damage taken by 3%."],
  [21562, "Power Word: Fortitude", "Infuses the target with vitality, increasing their Stamina by 5% for 1 hour.\r\n\r\nIf the target is in your party or raid, all party and raid members will be affected."],
  [462854, "Skyfury", "Harness the fury of the Windlord to grant a target ally 2% Mastery and empower their auto attacks to have a 20% chance to instantly strike again for 1 hour.\r\n\r\nIf the target is in your party or raid, all party and raid members will be affected."],
  [395152, "Ebon Might", "Increase all damage dealing allies' primary stat by 8.0% of your own and increase your own damage by 20% for 10 sec.\r\n\r\nEbon Might will split its effect when applied to more than 2 other allies.\r\n\r\nEruption, Deep Breath, and your empower spells extend the duration of these effects."],
  [8647, "Mystic Touch", "Your damage weakens the target, increasing Physical damage taken by 5%."],
  [255260, "Chaos Brand", "Your damage brands the target, increasing magic damage taken by 3%."],
  [257284, "Hunter's Mark", "Apply Hunter's Mark to the target, causing the target to always be seen and tracked by the Hunter.\r\n\r\nHunter's Mark increases the target's damage taken by 3%. Can only be applied to a target at a time."],
  [381637, "Atrophic Poison", "Coats your weapons with a Non-Lethal Poison that lasts for 1 hour. Each strike has a 30% chance of poisoning the enemy, reducing their damage by 3.0% for 10 sec."],
  [20484, "Rebirth", "Returns the spirit to the body, restoring a dead target to life with 100% health and at least 20% mana. Castable in combat."],
  [61999, "Raise Ally", "Pours dark energy into a dead target, reuniting spirit and body to allow the target to reenter battle with 60% health and at least 20% mana."],
  [20707, "Soulstone", "Stores the soul of the target party or raid member, allowing resurrection upon death. Targets resurrect with 60% health and at least 20% mana."],
  [391054, "Intercession", "Petition the Light on the behalf of a fallen ally, restoring spirit to body and allowing them to reenter battle with 60% health and at least 20% mana."],
  [106898, "Stampeding Roar", "Shift into Bear Form and let loose a wild roar, increasing the movement speed of all friendly players within 15 yards by 60% for 8 sec."],
  [192077, "Wind Rush Totem", "Summons a totem at the target location for 15 sec, continually granting all allies who pass within 10 yards 40% increased movement speed for 5 sec."],
  [374227, "Zephyr", "Conjure an updraft to lift you and your 4 nearest allies within 20 yds into the air, reducing damage taken from area-of-effect attacks by 20% and increasing movement speed by 30% for 8 sec."],
  [111771, "Demonic Gateway", "Creates a demonic gateway between two locations. Activating the gateway transports the user to the other gateway. Each player can use a Demonic Gateway only once per 90 sec."],
  [32375, "Mass Dispel", "Dispels magic in a 15 yard radius, removing all harmful Magic from 5 friendly targets and 1 beneficial Magic effect from 5 enemy targets. Potent enough to remove Magic that is normally undispellable."],
  [29166, "Innervate", "Infuse a friendly healer with energy, allowing them to cast spells without spending mana for 8 sec."],
  [49576, "Death Grip", "Harnesses the energy that surrounds and binds all matter, drawing the target toward you."],
  [1022, "Blessing of Protection", "Blesses a party or raid member, granting immunity to Physical damage and harmful effects for 10 sec.\r\n\r\nCannot be used on a target with Forbearance. Causes Forbearance for 30 sec."],
  [204018, "Blessing of Spellwarding", "Blesses a party or raid member, granting immunity to magical damage and harmful effects for 10 sec.\r\n\r\nCannot be used on a target with Forbearance. Causes Forbearance for 30 sec.\r\n\r\nShares a cooldown with Blessing of Protection."],
  [102342, "Ironbark", "The target's skin becomes as tough as Ironwood, reducing damage taken by 20% for 12 sec."],
  [116849, "Life Cocoon", "Encases the target in a cocoon of Chi energy for 12 sec, absorbing 14,664 damage and increasing all healing over time received by 50%."],
  [357170, "Time Dilation", "Stretch time around an ally for the next 8 sec, causing 50% of damage they would take to instead be dealt over 8 sec."],
  [33206, "Pain Suppression", "Reduces all damage taken by a friendly target by 40% for 8 sec. Castable while stunned."],
  [47788, "Guardian Spirit", "Calls upon a guardian spirit to watch over the friendly target for 10 sec, increasing healing received by 60%. If the target would die, the Spirit sacrifices itself and restores the target to 40% health.\r\n\r\nCastable while stunned. Cannot save the target from massive damage."],
  [6940, "Blessing of Sacrifice", "Blesses a party or raid member, reducing their damage taken by 30%, but you suffer 100% of damage prevented.\r\n\r\nLast 12 sec, or until transferred damage would cause you to fall below 20% health."],
  [3411, "Intervene", "Run at high speed toward an ally, intercepting all melee and ranged attacks against them for 6 sec while they remain within 10 yds."],
  [51052, "Anti-Magic Zone", "Places an Anti-Magic Zone for 6 sec, reducing the magic damage taken by party or raid members by 15%."],
  [97462, "Rallying Cry", "Lets loose a rallying cry, granting all party or raid members within 40 yards 10% temporary and maximum health for 10 sec.\r\n\r\nHealth granted increased by 50% when not in a raid."],
  [196718, "Darkness", "Summons darkness around you in an 8 yd radius, granting friendly targets a 15% chance to avoid all damage from an attack. Lasts 8 sec.\r\n\r\nChance to avoid damage increased by 100% when not in a raid."],
  [204150, "Aegis of Light"],
  [45438, "Ice Block", "Encases you in a block of ice, protecting you from all attacks and damage for 10 sec, but during that time you cannot attack, move, or cast spells.\r\n\r\nCauses Hypothermia, preventing you from recasting Ice Block for 30 sec."],
  [642, "Divine Shield", "Grants immunity to all damage, harmful effects, knockbacks and forced movement effects for 8 sec. \r\n\r\nCannot be used if you have Forbearance. Causes Forbearance for 30 sec."],
  [186265, "Aspect of the Turtle", "Causes all spells and attacks to miss and reduces all damage you take by 30% for 8 sec, but you cannot attack."],
  [31224, "Cloak of Shadows", "Provides a moment of magic immunity, instantly removing all harmful spell effects. The cloak lingers, causing you to resist harmful spells for 5 sec."],
  [196555, "Netherwalk", "Slip into the nether when you active Blur, increasing movement speed by 100% and becoming immune to damage for 2.5 sec."],
  [47585, "Dispersion", "Disperse into pure shadow energy, reducing all damage taken by 75% for 6 sec and healing you for 25% of your maximum health over its duration, but you are unable to attack or cast spells.\r\n\r\nIncreases movement speed by 50% and makes you immune to all movement impairing effects.\r\n\r\nCastable while stunned, feared, or silenced. "],
  [163201, "Execute", "Attempts to finish off a foe, causing up to 170 Physical damage based on Rage spent. Only usable on enemies that have less than 20% health."],
  [32379, "Shadow Word: Death", "A word of dark binding that inflicts 325 Shadow damage to your target. If your target is not killed by Shadow Word: Death, you take backlash damage equal to 5% of your maximum health.\r\n\r\nDamage increased by 150% to targets below 20% health."],
  [53351, "Kill Shot", "You attempt to finish off a wounded target, dealing 248 Physical damage. Only usable on enemies with less than 20% health."],
  [24275, "Hammer of Wrath", "Hurls a divine hammer that strikes an enemy for 50 Holy damage.\r\n\r\nGenerates 1 Holy Power."],
  [322109, "Touch of Death", "You exploit the enemy target's weakest point, instantly dealing damage equal to 100% of your maximum health to them.\r\n\r\nOnly usable on creatures that have less health than you."],
  [702, "Curse of Weakness", "Increases the time between an enemy's attacks by 20% for 2 min.\r\n\r\nCurses: A warlock can only have one Curse active per target."],
  [1714, "Curse of Tongues", "Forces the target to speak in Demonic, increasing the casting time of all spells by 30% for 1 min.\r\n\r\nCurses: A warlock can only have one Curse active per target."],
  [132469, "Typhoon", "Blasts targets within 15 yards in front of you with a violent Typhoon, knocking them back and reducing their movement speed by 50% for 6 sec. Usable in all shapeshift forms."],
  [51490, "Thunderstorm", "Calls down a bolt of lightning, dealing 58 Nature damage to all enemies within 10 yards, reducing their movement speed by 40% for 5 sec, and knocking them away from the Shaman. Usable while stunned."],
  [116844, "Ring of Peace", "Form a Ring of Peace at the target location for 5 sec. Enemies that enter will be ejected from the Ring."],
  [357214, "Wing Buffet", "With a powerful flap of your wings, knock away enemies in front of you."],
  [368970, "Tail Swipe", "Lash out with your tail, knocking enemies within 8 yds into the air."],
  [378779, "Thundershock", "Thunderstorm knocks enemies up instead of away and its cooldown is reduced by 5 sec."],
  [12294, "Mortal Strike", "A vicious strike that deals 178 Physical damage and reduces the effectiveness of healing on the target by 50% for 10 sec."],
  [8679, "Wound Poison", "Coats your weapons with a Lethal Poison that lasts for 1 hour. Each strike has a 30% chance to poison the enemy, which instantly inflicts 1 Nature damage and reduces all healing received by 8% for 12 sec, stacking up to 3 times."],
  [107428, "Rising Sun Kick", "Kick upwards, dealing 50 Physical damage."],
  [2908, "Soothe", "Soothes the target, dispelling all enrage effects."],
  [19801, "Tranquilizing Shot", "Removes 1 Enrage and 1 Magic effect from an enemy target."],
  [5938, "Shiv", "Attack with your off-hand, dealing 2 Physical damage, dispelling all enrage effects and applying a concentrated form of your active Non-Lethal poison.\r\n\r\nAwards 1 combo point."],
  [370, "Purge", "Purges the enemy target, removing 1 beneficial Magic effect."],
  [528, "Dispel Magic", "Dispels Magic on the enemy target, removing 1 beneficial Magic effect."],
  [30449, "Spellsteal", "Steals a beneficial magic effect from the target. This effect lasts a maximum of 2 min."],
  [278326, "Consume Magic", "Consume 1 beneficial Magic effect removing it from the target."],
  [10060, "Power Infusion", "Infuses the target with power for 15 sec, increasing haste by 20%.\r\n\r\nCan only be cast on players."],
  [64382, "Shattering Throw", "Hurl your weapon at the enemy,  removing any magical immunities and causing 210 Physical damage, ignoring armor. Deals up to 500% increased damage to absorb shields."],
  [384110, "Wrecking Throw"],
  [1264378, "Unravel", "Direct damage from Fire Breath consumes absorb shields from enemies, dealing 4,645 additional Spellfrost damage to them."],
  [451840, "Devour Matter", "Shadow Word: Death consumes absorb shields from your target, dealing 960 extra damage to them and granting you 1% mana if a shield was present."],
  [31230, "Cheat Death", "Fatal attacks instead reduce you to 7% of your maximum health. For 3 sec afterward, you take 85% reduced damage. Cannot trigger more often than once per 6 min."],
  [86949, "Cauterize", "Fatal damage instead brings you to 35% health and then burns you for 28% of your maximum health over 6 sec.\r\n\r\nWhile burning, movement slowing effects are suppressed and your movement speed is increased by 150%.\r\n\r\nThis effect cannot occur more than once every 6 min."],
  [114556, "Purgatory", "An unholy pact that prevents fatal damage, instead absorbing incoming healing equal to the damage prevented, lasting 3 sec.\r\n\r\nIf any healing absorption remains when this effect expires, you will die. This effect may only occur every 4 min."],
  [209258, "Last Resort", "Sustaining fatal damage instead transforms you to Metamorphosis form.\r\n\r\nThis may occur once every 8 min."],
  [179057, "Chaos Nova", "Unleash an eruption of fel energy, dealing 9 Chaos damage and stunning all nearby enemies for 3 sec."],
  [1234195, "Void Nova", "Unleash an eruption of void energy, dealing 104 Cosmic damage and stunning your target and all nearby enemies for 2 sec."],
  [119381, "Leg Sweep", "Knocks down all enemies within 6 yards, stunning them for 3 sec."],
  [192058, "Capacitor Totem", "Summons a totem at the target location that gathers electrical energy from the surrounding air and explodes after 2 sec, stunning all enemies within 8 yards for 3 sec."],
  [30283, "Shadowfury", "Stuns all enemies within 8 yds for 3 sec."],
  [117526, "Binding Shot", "Fires a magical projectile, tethering the enemy and any other enemies within 5 yds for 10 sec, stunning them for 3 sec if they move more than 5 yds from the arrow."],
  [46968, "Shockwave", "Sends a wave of force in a frontal cone, causing 6 damage and stunning all enemies within 10 yards for 2 sec."],
  [102359, "Mass Entanglement", "Roots the target and all enemies within 12 yards in place for 10 sec. Damage may interrupt the effect. Usable in all shapeshift forms."],
  [439895, "Entangling Vortex", "Enemies pulled into Ursol's Vortex are rooted in place for 3 sec. Damage may cancel the effect."],
  [358385, "Landslide", "Conjure a path of shifting stone towards the target location, rooting enemies for 15 sec. Damage may cancel the effect."],
  [122, "Frost Nova", "Blasts enemies within 12 yds of you for 20 Frost damage and freezes them in place for 6 sec. Damage may interrupt the freeze effect."],
  [1250691, "Void Tendrils", "Call shadowy tendrils to constrict enemies when Psychic Scream ends, rooting them in place for 4 sec."],
  [51485, "Earthgrab Totem", "Summons a totem at the target location for 20 sec. The totem pulses every 2 sec, rooting all enemies within 8 yards for 8 sec. Enemies previously rooted by the totem instead suffer 50% movement speed reduction."],
  [202138, "Sigil of Chains", "Place a Sigil of Chains at the target location that activates after 2 sec.\r\n\r\nAll enemies affected by the sigil are pulled to its center and are snared, reducing movement speed by 70% for 6 sec."],
  [452403, "Wave of Debilitation", "Chaos Nova slows enemies by 60% and reduces attack and cast speed by 15% for 5 sec after its stun fades. "],
  [102793, "Ursol's Vortex", "Conjures a vortex of wind for 10 sec at the destination, reducing the movement speed of all enemies within 8 yards by 50%. The first time an enemy attempts to leave the vortex, winds will pull that enemy back to its center. Usable in all shapeshift forms."],
  [187698, "Tar Trap", "Hurls a tar trap to the target location that creates a 8 yd radius pool of tar around itself for 30 sec when the first enemy approaches. All enemies have 50% reduced movement speed while in the area of effect. Limit 1. Trap will exist for 1 min."],
  [2484, "Earthbind Totem", "Summons a totem at the target location for 20 sec that slows the movement speed of enemies within 10 yards by 50%."],
  [12323, "Piercing Howl", "Snares all enemies within 12 yards, reducing their movement speed by 70% for 8 sec.\r\n\r\nSpurs all allies within 6 yards, increasing their movement speed by 30% for 4 sec."],
  [429639, "Boneshaker", "Shockwave's stun duration is increased by 1 sec and reduces the movement speed of affected enemies by 40% for 3 sec after the stun ends."],
  [108199, "Gorefiend's Grasp", "Shadowy tendrils coil around all enemies within 15 yards of a hostile or friendly target, pulling them to the target's location and Silencing them for 3 sec."],
  [315443, "Abomination Limb", "Sprout an additional limb, dealing 130 Shadow damage over 12 sec to all nearby enemies. Deals reduced damage beyond 5 targets. Every 1 sec, an enemy is pulled to your location if they are further than 8 yds from you. The same enemy can only be pulled once every 4 sec.\r\n\r\nGain  instantly, and again every 6 sec."],
  [34477, "Misdirection", "Misdirects all threat you cause to the targeted party or raid member, beginning with your next attack within 30 sec and lasting for 8 sec."],
  [57934, "Tricks of the Trade", "Redirects all threat you cause to the targeted party or raid member, beginning with your next damaging attack within the next 30 sec and lasting 6 sec."],
  [78675, "Solar Beam", "Summons a beam of solar light over an enemy target's location, interrupting the target and silencing all enemies within the beam. Lasts 8 sec."],
  [202137, "Sigil of Silence", "Place a Sigil of Silence at the target location that activates after 2 sec.\r\n\r\nSilences all enemies affected by the sigil for 2 sec."],
  [15487, "Silence", "Silences the target, preventing them from casting spells for 5 sec. Against non-players, also interrupts spellcasting and prevents any spell in that school from being cast for 4 sec."],
  [392060, "Wailing Arrow", "Fire an enchanted arrow, dealing 483 Shadow damage to your target and an additional 245 Shadow damage to all enemies within 8 yds of your target. Non-Player targets struck by a Wailing Arrow have their spellcasting interrupted and are silenced for 1 sec.\r\n\r\nGrants Deathblow."],
  [1044, "Blessing of Freedom", "Blesses a party or raid member, granting immunity to movement impairing effects for 8 sec."],
  [116841, "Tiger's Lust", "Increases a friendly target's movement speed by 70% for 6 sec and removes all roots and snares."],
  [53271, "Master's Call", "Your pet removes all root and movement impairing effects from itself and a friendly target, and grants immunity to all such effects for 4 sec."],
  [370665, "Rescue", "Swoop to an ally and fly with them to the target location. Clears movement impairing effects from you and your ally."],
  [73325, "Leap of Faith", "Pulls the spirit of a party or raid member, instantly moving them directly in front of you."],
  [121536, "Angelic Feather", "Places a feather at the target location, granting the first ally to walk through it 40% increased movement speed for 5 sec. Only 3 feathers can be placed at one time."],
  [47528, "Mind Freeze", "Smash the target's mind with cold, interrupting spellcasting and preventing any spell in that school from being cast for 5 sec."],
  [183752, "Disrupt", "Interrupts the enemy's spellcasting and locks them from that school of magic for 5 sec."],
  [106839, "Skull Bash", "You charge and bash the target's skull, interrupting spellcasting and preventing any spell in that school from being cast for 5 sec."],
  [351338, "Quell", "Interrupt an enemy's spellcasting and prevent any spell from that school of magic from being cast for 6 sec."],
  [147362, "Counter Shot", "Interrupts spellcasting, preventing any spell in that school from being cast for 5 sec."],
  [187707, "Muzzle", "Interrupts spellcasting, preventing any spell in that school from being cast for 5 sec."],
  [2139, "Counterspell", "Counters the enemy's spellcast, preventing any spell from that school of magic from being cast for 7 sec."],
  [116705, "Spear Hand Strike", "Jabs the target in the throat, interrupting spellcasting and preventing any spell from that school of magic from being cast for 5 sec."],
  [96231, "Rebuke", "Interrupts spellcasting and prevents any spell in that school from being cast for 5 sec."],
  [1766, "Kick", "A quick kick that interrupts spellcasting and prevents any spell in that school from being cast for 6 sec."],
  [57994, "Wind Shear", "Disrupts the target's concentration with a burst of wind, interrupting spellcasting and preventing any spell in that school from being cast for 4 sec."],
  [19647, "Spell Lock"],
  [89766, "Axe Toss"],
  [6552, "Pummel", "Pummels the target, interrupting spellcasting and preventing any spell in that school from being cast for 5 sec."],
  [4987, "Cleanse", "Cleanses a friendly target, removing all Magic effects."],
  [88423, "Nature's Cure", "Cures harmful effects on the friendly target, removing all Magic effects."],
  [360823, "Naturalize", "Cleanses harmful effects from the target, removing all Magic and Poison effects."],
  [115450, "Detox", "Removes all Magic effects from the target."],
  [527, "Purify", "Dispels harmful effects on the target, removing all Magic effects."],
  [254420, "Purify Spirit"],
  [115310, "Revival", "Heals all party and raid members within 40 yds for 23,257 and clears them of 3 harmful Magic, all Poison, and all Disease effects.\r\n\r\nHealing reduced beyond 5 targets."],
  [89808, "Singe Magic"],
  [2782, "Remove Corruption", "Nullifies corrupting effects on the friendly target, removing all Curse and Poison effects."],
  [374251, "Cauterizing Flame", "Cauterize an ally's wounds, removing all Bleed, Poison, Curse, and Disease effects. Heals for 1,330 upon removing any effect."],
  [475, "Remove Curse", "Removes all Curses from a friendly target. "],
  [51886, "Cleanse Spirit", "Removes all Curse effects from a friendly target."],
  [365585, "Expunge", "Expunge toxins affecting an ally, removing all Poison effects."],
  [218164, "Detox", "Removes all Poison and Disease effects from the target."],
  [388615, "Restoral", "Heals all party and raid members within 40 yds for 22,471 and clears them of all harmful Poison and Disease effects. \r\n\r\nCastable while stunned.\r\n\r\nHealing reduced beyond 5 targets."],
  [213644, "Cleanse Toxins", "Cleanses a friendly target, removing all Poison and Disease effects."],
  [383013, "Poison Cleansing Totem", "Summons a totem at your feet that removes all Poison effects from a nearby party or raid member within 30 yards every 1.5 sec for 6 sec."],
  [213634, "Purify Disease", "Removes all Disease effects from a friendly target."],
  [8143, "Tremor Totem", "Summons a totem at your feet that shakes the ground around it for 10 sec, removing Fear, Charm and Sleep effects from party and raid members within 30 yards."],
  [384100, "Berserker Shout"],
];

export const demoAnalyticsMetadata = {
  raidEffects: raidEffectSeeds.map(raidEffect),
  compositionAbilities: abilitySeeds.map(ability),
  compositionMappings: mappingSeeds.map(mapping),
  wowSpells: spellSeeds.map(spell),
};
