export interface DemoRosterMember {
  id: string;
  character_name: string;
  character_realm: string;
  character_realm_slug: string;
  character_class_id: number;
  character_level: number;
  rank_index: number;
  rank_name: string | null;
  is_guild_master: boolean | null;
  matched_user_id: string | null;
  matched_character_id: string | null;
  is_main_character?: boolean;
  profile?: {
    id: string;
    username: string;
    avatar_url: string | null;
  } | null;
}

const profile = (id: string, username: string) => ({
  id,
  username,
  avatar_url: null,
});

export const demoMemberRankLabels: Record<number, string> = {
  0: 'Guild Master',
  1: 'GM Alt',
  2: 'Officer',
  3: 'Officer Alt',
  4: 'Raid Leader',
  5: 'Core Raider',
  6: 'Raider',
  7: 'Trial',
  8: 'Alt',
};

export const demoRosterMembers: DemoRosterMember[] = [
  {
    id: 'cache-nyxara',
    character_name: 'Nyxara',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 6,
    character_level: 90,
    rank_index: 0,
    rank_name: 'Guild Master',
    is_guild_master: true,
    matched_user_id: 'gf-nyx',
    matched_character_id: 'char-nyxara',
    is_main_character: true,
    profile: profile('gf-nyx', 'Nyx'),
  },
  {
    id: 'cache-thornwall',
    character_name: 'Thornwall',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 2,
    character_level: 90,
    rank_index: 2,
    rank_name: 'Officer',
    is_guild_master: false,
    matched_user_id: 'gf-thorn',
    matched_character_id: 'char-thornwall',
    is_main_character: true,
    profile: profile('gf-thorn', 'Thorn'),
  },
  {
    id: 'cache-lunaria',
    character_name: 'Lunaria',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 5,
    character_level: 90,
    rank_index: 2,
    rank_name: 'Officer',
    is_guild_master: false,
    matched_user_id: 'gf-luna',
    matched_character_id: 'char-lunaria',
    is_main_character: true,
    profile: profile('gf-luna', 'Luna'),
  },
  {
    id: 'cache-ashflare',
    character_name: 'Ashflare',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 8,
    character_level: 90,
    rank_index: 4,
    rank_name: 'Raid Leader',
    is_guild_master: false,
    matched_user_id: 'gf-ash',
    matched_character_id: 'char-ashflare',
    is_main_character: true,
    profile: profile('gf-ash', 'Ash'),
  },
  {
    id: 'cache-voidmark',
    character_name: 'Voidmark',
    character_realm: 'Draenor',
    character_realm_slug: 'draenor',
    character_class_id: 9,
    character_level: 90,
    rank_index: 4,
    rank_name: 'Raid Leader',
    is_guild_master: false,
    matched_user_id: 'gf-void',
    matched_character_id: 'char-voidmark',
    is_main_character: true,
    profile: profile('gf-void', 'Void'),
  },
  {
    id: 'cache-mistvale',
    character_name: 'Mistvale',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 10,
    character_level: 90,
    rank_index: 5,
    rank_name: 'Core Raider',
    is_guild_master: false,
    matched_user_id: 'gf-mist',
    matched_character_id: 'char-mistvale',
    is_main_character: true,
    profile: profile('gf-mist', 'Mist'),
  },
  {
    id: 'cache-seraphyne',
    character_name: 'Seraphyne',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 2,
    character_level: 90,
    rank_index: 5,
    rank_name: 'Core Raider',
    is_guild_master: false,
    matched_user_id: 'gf-sera',
    matched_character_id: 'char-seraphyne',
    is_main_character: true,
    profile: profile('gf-sera', 'Sera'),
  },
  {
    id: 'cache-tidecall',
    character_name: 'Tidecall',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 7,
    character_level: 90,
    rank_index: 5,
    rank_name: 'Core Raider',
    is_guild_master: false,
    matched_user_id: 'gf-tide',
    matched_character_id: 'char-tidecall',
    is_main_character: true,
    profile: profile('gf-tide', 'Tide'),
  },
  {
    id: 'cache-bloomshift',
    character_name: 'Bloomshift',
    character_realm: 'Silvermoon',
    character_realm_slug: 'silvermoon',
    character_class_id: 11,
    character_level: 90,
    rank_index: 5,
    rank_name: 'Core Raider',
    is_guild_master: false,
    matched_user_id: 'gf-bloom',
    matched_character_id: 'char-bloomshift',
    is_main_character: true,
    profile: profile('gf-bloom', 'Bloom'),
  },
  {
    id: 'cache-skyrend',
    character_name: 'Skyrend',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 13,
    character_level: 90,
    rank_index: 5,
    rank_name: 'Core Raider',
    is_guild_master: false,
    matched_user_id: 'gf-sky',
    matched_character_id: 'char-skyrend',
    is_main_character: true,
    profile: profile('gf-sky', 'Sky'),
  },
  {
    id: 'cache-ironchant',
    character_name: 'Ironchant',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 1,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-iron',
    matched_character_id: 'char-ironchant',
    is_main_character: true,
    profile: profile('gf-iron', 'Iron'),
  },
  {
    id: 'cache-nightstep',
    character_name: 'Nightstep',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 4,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-night',
    matched_character_id: 'char-nightstep',
    is_main_character: true,
    profile: profile('gf-night', 'Night'),
  },
  {
    id: 'cache-starwoven',
    character_name: 'Starwoven',
    character_realm: 'Kazzak',
    character_realm_slug: 'kazzak',
    character_class_id: 5,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-star',
    matched_character_id: 'char-starwoven',
    is_main_character: true,
    profile: profile('gf-star', 'Star'),
  },
  {
    id: 'cache-frostlark',
    character_name: 'Frostlark',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 8,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-frost',
    matched_character_id: 'char-frostlark',
    is_main_character: true,
    profile: profile('gf-frost', 'Frost'),
  },
  {
    id: 'cache-wildarrow',
    character_name: 'Wildarrow',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 3,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-wild',
    matched_character_id: 'char-wildarrow',
    is_main_character: true,
    profile: profile('gf-wild', 'Wild'),
  },
  {
    id: 'cache-sunforge',
    character_name: 'Sunforge',
    character_realm: 'Silvermoon',
    character_realm_slug: 'silvermoon',
    character_class_id: 2,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-sun',
    matched_character_id: 'char-sunforge',
    is_main_character: true,
    profile: profile('gf-sun', 'Sun'),
  },
  {
    id: 'cache-felborne',
    character_name: 'Felborne',
    character_realm: 'Draenor',
    character_realm_slug: 'draenor',
    character_class_id: 12,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-fel',
    matched_character_id: 'char-felborne',
    is_main_character: true,
    profile: profile('gf-fel', 'Fel'),
  },
  {
    id: 'cache-rootflare',
    character_name: 'Rootflare',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 11,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-root',
    matched_character_id: 'char-rootflare',
    is_main_character: true,
    profile: profile('gf-root', 'Root'),
  },
  {
    id: 'cache-stormbyte',
    character_name: 'Stormbyte',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 7,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-storm',
    matched_character_id: 'char-stormbyte',
    is_main_character: true,
    profile: profile('gf-storm', 'Storm'),
  },
  {
    id: 'cache-riftcoil',
    character_name: 'Riftcoil',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 9,
    character_level: 80,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: 'gf-void',
    matched_character_id: 'char-riftcoil',
    is_main_character: false,
    profile: profile('gf-void', 'Void'),
  },
  {
    id: 'cache-nethercoil',
    character_name: 'Nethercoil',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 9,
    character_level: 90,
    rank_index: 6,
    rank_name: 'Raider',
    is_guild_master: false,
    matched_user_id: 'gf-nether',
    matched_character_id: 'char-nethercoil',
    is_main_character: true,
    profile: profile('gf-nether', 'Nether'),
  },
  {
    id: 'cache-kaelith',
    character_name: 'Kaelith',
    character_realm: 'Kazzak',
    character_realm_slug: 'kazzak',
    character_class_id: 8,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-kael',
    matched_character_id: 'char-kaelith',
    is_main_character: true,
    profile: profile('gf-kael', 'Kael'),
  },
  {
    id: 'cache-dawnbraid',
    character_name: 'Dawnbraid',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 2,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-dawn',
    matched_character_id: 'char-dawnbraid',
    is_main_character: true,
    profile: profile('gf-dawn', 'Dawn'),
  },
  {
    id: 'cache-embershard',
    character_name: 'Embershard',
    character_realm: 'Draenor',
    character_realm_slug: 'draenor',
    character_class_id: 8,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-ember',
    matched_character_id: 'char-embershard',
    is_main_character: true,
    profile: profile('gf-ember', 'Ember'),
  },
  {
    id: 'cache-bonewake',
    character_name: 'Bonewake',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 6,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-bone',
    matched_character_id: 'char-bonewake',
    is_main_character: true,
    profile: profile('gf-bone', 'Bone'),
  },
  {
    id: 'cache-gloomveil',
    character_name: 'Gloomveil',
    character_realm: 'Silvermoon',
    character_realm_slug: 'silvermoon',
    character_class_id: 4,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-gloom',
    matched_character_id: 'char-gloomveil',
    is_main_character: true,
    profile: profile('gf-gloom', 'Gloom'),
  },
  {
    id: 'cache-auraforge',
    character_name: 'Auraforge',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 13,
    character_level: 90,
    rank_index: 7,
    rank_name: 'Trial',
    is_guild_master: false,
    matched_user_id: 'gf-aura',
    matched_character_id: 'char-auraforge',
    is_main_character: true,
    profile: profile('gf-aura', 'Aura'),
  },
  {
    id: 'cache-nyxbank',
    character_name: 'Nyxbank',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 4,
    character_level: 74,
    rank_index: 1,
    rank_name: 'GM Alt',
    is_guild_master: false,
    matched_user_id: 'gf-nyx',
    matched_character_id: 'char-nyxbank',
    is_main_character: false,
    profile: profile('gf-nyx', 'Nyx'),
  },
  {
    id: 'cache-thornmark',
    character_name: 'Thornmark',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 1,
    character_level: 78,
    rank_index: 3,
    rank_name: 'Officer Alt',
    is_guild_master: false,
    matched_user_id: 'gf-thorn',
    matched_character_id: 'char-thornmark',
    is_main_character: false,
    profile: profile('gf-thorn', 'Thorn'),
  },
  {
    id: 'cache-moonlace',
    character_name: 'Moonlace',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 11,
    character_level: 77,
    rank_index: 3,
    rank_name: 'Officer Alt',
    is_guild_master: false,
    matched_user_id: 'gf-luna',
    matched_character_id: 'char-moonlace',
    is_main_character: false,
    profile: profile('gf-luna', 'Luna'),
  },
  {
    id: 'cache-ashvault',
    character_name: 'Ashvault',
    character_realm: 'Draenor',
    character_realm_slug: 'draenor',
    character_class_id: 3,
    character_level: 72,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: 'gf-ash',
    matched_character_id: 'char-ashvault',
    is_main_character: false,
    profile: profile('gf-ash', 'Ash'),
  },
  {
    id: 'cache-silentsong',
    character_name: 'Silentsong',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 3,
    character_level: 70,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: null,
    matched_character_id: null,
    is_main_character: false,
    profile: null,
  },
  {
    id: 'cache-grimlight',
    character_name: 'Grimlight',
    character_realm: 'Kazzak',
    character_realm_slug: 'kazzak',
    character_class_id: 9,
    character_level: 80,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: null,
    matched_character_id: null,
    is_main_character: false,
    profile: null,
  },
  {
    id: 'cache-verdantfox',
    character_name: 'Verdantfox',
    character_realm: 'Silvermoon',
    character_realm_slug: 'silvermoon',
    character_class_id: 11,
    character_level: 71,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: null,
    matched_character_id: null,
    is_main_character: false,
    profile: null,
  },
  {
    id: 'cache-runebolt',
    character_name: 'Runebolt',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 6,
    character_level: 80,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: null,
    matched_character_id: null,
    is_main_character: false,
    profile: null,
  },
  {
    id: 'cache-cloudbloom',
    character_name: 'Cloudbloom',
    character_realm: 'Tarren Mill',
    character_realm_slug: 'tarren-mill',
    character_class_id: 10,
    character_level: 76,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: 'gf-mist',
    matched_character_id: 'char-cloudbloom',
    is_main_character: false,
    profile: profile('gf-mist', 'Mist'),
  },
  {
    id: 'cache-duskward',
    character_name: 'Duskward',
    character_realm: 'Draenor',
    character_realm_slug: 'draenor',
    character_class_id: 12,
    character_level: 70,
    rank_index: 8,
    rank_name: 'Alt',
    is_guild_master: false,
    matched_user_id: null,
    matched_character_id: null,
    is_main_character: false,
    profile: null,
  },
];
